//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comment = new HashSet<Comment>();
            this.Tag = new HashSet<Tag>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public long UserID { get; set; }
        public byte[] CreationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ArticleLike ArticleLike { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
